name: CD for React Application

on:
  workflow_run:
    workflows: ["CI for React Application"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest

      - name: Deploy to Docker Hub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
          docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
